language: python
os: linux
branches:
  only:
    # Build tags and branches named master or starting with
    # 'v' followed by a digit, such as for version tags.
    - master
    - /^v\d.*$/
jobs:
  include:
    - python: '3.6'
      env:
        - TOXENV=py36,report,codecov
    - python: '3.7'
      env:
        - TOXENV=py37,report,codecov
    - python: '3.8'
      env:
        - TOXENV=py38,report,codecov
    - python: 'pypy3'
      env:
        - TOXENV=pypy3,report,codecov
    - python: '3.8'
      env:
        - TOXENV=doc
    - python: '3.8'
      env:
        - TOXENV=check
install:
  - docker pull altendky/hydra
script:
  - docker run --rm -it -v $(pwd):/wd -e TOXENV "${TOXENV}" altendky/hydra /bin/bash in_docker.sh
  - |
    set -ex
    if [[ $TOXENV == 'check' ]]; then
        (gem install travis --no-rdoc --no-ri
         travis lint --no-interactive --exit-code)
    fi
    set +x
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
notifications:
  email:
    on_success: never
    on_failure: always
