language: python
os: linux
branches:
  only:
    # Build tags and branches named master or starting with
    # 'v' followed by a digit, such as for version tags.
    - master
    - /^v\d.*$/
cache: pip
addons:
  apt:
    packages:
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - libncurses5-dev
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libffi-dev
      - liblzma-dev
      - python-openssl
      - git
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
jobs:
  include:
    - python: '3.6'
      env:
        - TOXENV=py36,report,codecov
    - python: '3.7'
      env:
        - TOXENV=py37,report,codecov
    - python: '3.8'
      env:
        - TOXENV=py38,report,codecov
    - python: 'pypy3'
      env:
        - TOXENV=pypy3,report,codecov
    - python: '3.8'
      env:
        - TOXENV=doc
    - python: '3.8'
      env:
        - TOXENV=check
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - export PYENV_ROOT="~/desert_cache/.pyenv"
  - curl https://pyenv.run | bash
  - "$PYENV_ROOT/bin/pyenv" install 3.8.1
  - export TOXTOOLPYTHON="$PYENV_ROOT/versions/3.8.1/bin/python"
  - unset PYENV_ROOT
  - pip install tox
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
  - |
    set -ex
    if [[ $TOXENV == 'check' ]]; then
        (gem install travis --no-rdoc --no-ri
         travis lint --no-interactive --exit-code)
    fi
    set +x
script:
  - tox -v
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
notifications:
  email:
    on_success: never
    on_failure: always
